### ISSUE TITLE
Classes and ID's utilized by ESPs being removed.

### ISSUE THREAD

**Issue by stephenprovenzano** [maxlapides/dovetailer#11]
We had a situation where we were provided a snippet of code from an ESP (Hubspot in this situation) where they utilized an ID on the element (Pre-header text `<div`). Once compiled, the automatic feature to remove unused classes and ID's had removed the ID and broke the functionality within the ESP.

Is it possible to only remove classes that produce inline CSS in the compiled version and keep any classes or ID's that have no CSS settings applied to them?

**Comment by maxlapides** [comment]
@stephenprovenzano I can whitelist specific IDs and classes that we do not want to be stripped. I would like to make this a user-configurable feature in the future, but since we don't currently have any sort of configurability framework in Dovetailer (yet?), I'll just globally whitelist those identifiers for now. Could you send me a list of classes and IDs to whitelist? This is the current whitelist: https://github.com/maxlapides/dovetailer/blob/639bb881e91bac5786eb82e2a2036b618c12e0cf/lib/build.js#L226

**Comment by stephenprovenzano** [comment]
@maxlapides After looking into this again, this issue goes a bit further as well.

`<div id="preview_text" style="display:none !important; mso-hide:all; max-height:0; overflow:hidden; ">{% text "preview_text" label="Preview Text <span class="help-text">This will be used as the preview text that displays in some email clients</span>", value="", no_wrapper=True %}</div>`

In the code above, `id="#preview_text"` is being removed since no CSS/media queries are being applied.

Additionally, `{% text "preview_text"` The quotes around preview_text in this code are being converted to &quote;. The only way to get this issues resolved is to place the necessary code into the final compiled file.

**Comment by maxlapides** [comment]
@stephenprovenzano this is two separate issues:
1. `id="preview-text"` is being stripped. what are all of the IDs and classes that you do not want stripped?
2. the quotes issue. can you open a new issue for this problem?

**Comment by stephenprovenzano** [comment]
@maxlapides 

We will have to continually update you with new ID's if we're going the whitelist approach. At this time preview-text is the only one I am seeing for this specific template.

For 2. I will open another issue, thank you.

**Comment by maxlapides** [comment]
Will be fixed in 0.5.15

**Comment by stephenprovenzano** [comment]
Max,

I apologize for the confusion, but it seems down the line we altered the ID to "preview-text" when it should have been "preview_text". 

Can we change this?

**Comment by maxlapides** [comment]
Will be fixed in 0.5.17
