### ISSUE TITLE
Outlook Hi-DPI Requirement

### ISSUE THREAD

**Issue by stephenprovenzano** [maxlapides/dovetailer#13]
Two items must be applied to the top of every template to insure compatibility with hi-DPI windows settings affecting Outlook.

`<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">`

Which allows for this fix:

``

**Comment by maxlapides** [comment]
This fix is now automatically applied to every email
