### ISSUE TITLE
Include example config.js to complete gulp examples

### ISSUE THREAD

**Issue by joeyfigaro** [maxlapides/dovetailer#4]
The example gulpfile currently requires `config.js`, which doesn't exist. It'd be great if an example config were available to see what kind of object is expected.

**Comment by maxlapides** [comment]
@joeyfigaro thanks for checking out dovetailer! i just added an `example-config.js` file to this project as a demo. and in the near future, i'm going to create a new repository with a full example project that you can fork :)

**Comment by joeyfigaro** [comment]
@maxlapides Fantastic, man! Thank you for everything you've put together here. Can't have enough useful packages/utilities for developing email templates.
