### ISSUE TITLE
Destructuring in build.js throws undefined/null

### ISSUE THREAD

**Issue by joeyfigaro** [maxlapides/dovetailer#8]
Another one for ya! 

**Parameters**
- No CSS/styles used

**Test HTML (from example here)**
```handlebars
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="initial-scale=1.0">    <!-- So that mobile webkit will display zoomed in -->
    <meta name="format-detection" content="telephone=yes"> <!-- disable auto telephone linking in iOS -->
    <title>Test</title>
</head>
<body>
    <table>
        <tr>
            <td align="center">
                <p>This is a {{from_name}}. Some "quoted text."</p>
                <p>{{from_email}}</p>
                <p>© Awesomepants McChunkmuffins</p>
            </td>
        </tr>
    </table>
</body>
</html>
```
**content.json**
```json
{
    "from_name": "{{from_name}}",
    "from_email": "{{from_email}}"
}
```

**Error**
```shell
error:  TypeError: Cannot match against 'undefined' or 'null'.
```

**Build.js console.log digging**
Changed `Promise.all.then(([ { html, text }, css ]) => { ... });` to `Promise.all.then((response) => { console.log(response); });` and got this:

```shell
error:
[ undefined,
  { customResets: { resetHead: false, resetInline: false },
    main: { head: '', inline: '' },
    reset:
     { head: '/*\n * Various CSS Resets to troubleshoot rendering problems.\n * ----------------\n * All files: reset-head.scss, reset-inline.scss\n * All styles are inlined into index.html by the html-email-generator.\n * Sources: Mailchimp Email Blueprints https://github.com/mailchimp/Email-Blueprints; HTML Email Boilerplate: http://www.paulund.co.uk/html-email-boilerplate\n*/\n.ReadMsgBody {\n  width: 100%;\n}\n\n.ExternalCla}}]
info: Emails compiled and saved.
```

**Comment by maxlapides** [comment]
@joeyfigaro what version of Node are you using?

**Comment by maxlapides** [comment]
@joeyfigaro does your template folder include a `style.scss` and a `text.handlebars` file? i don't think it will work if those files are missing. they can be blank, but they must exist. (i should definitely handle this case, though!)

**Comment by joeyfigaro** [comment]
@maxlapides `6.3.1`

**Comment by joeyfigaro** [comment]
Ah! That's gotta be it. I don't have a `style.scss`

**Comment by maxlapides** [comment]
@joeyfigaro let me know if that doesn't work!

**Comment by joeyfigaro** [comment]
@maxlapides Spoke too soon unfortunately - still having the same issue after adding style.scss. Here's the folder for the template: 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2G2D331n2W3R25222f2e/Image%202017-01-20%20at%201.55.52%20PM.png?X-CloudApp-Visitor-Id=9430e1414e6a9323ff28bb6d5f2f1f04&v=11ae48e5)

**Comment by joeyfigaro** [comment]
Whoop. Think I just figured it out. I added some content to `text.handlebars` and the error went away.

**Comment by maxlapides** [comment]
oh cool, i was able to reproduce the issue with the empty `text.handlebars` file. good catch! i'll fix this soon.

**Comment by maxlapides** [comment]
Dovetailer now supports empty `text.handlebars` and `html.handlebars` files!
