### ISSUE TITLE
Broken image urls result in gulp crashing

### ISSUE THREAD

**Issue by joeyfigaro** [maxlapides/dovetailer#9]
Just updated a remote image to take advantage of the retina scaling dovetailer does and am waiting for the updated resource to deploy. I updated my html to use the new URL, and gulp crashed with the following since the URL wasn't yet valid:

```
> <y>@0.0.1 start /Users/<a>/Repositories/<x>/<y>
> gulp

[17:15:31] Using gulpfile ~/Repositories/<x>/<y>/gulpfile.js
[17:15:31] Starting 'compile'...
[17:15:31] Starting 'watch'...
[17:15:31] Finished 'watch' after 14 ms
/Users/<a>/Repositories/<x>/<y>/node_modules/image-size/lib/index.js:34
  throw new TypeError('unsupported file type: ' + type + ' (file: ' + filepath + ')');
  ^

TypeError: unsupported file type: undefined (file: undefined)
```

**Comment by maxlapides** [comment]
@joeyfigaro i'm not able to reproduce this issue. my one suggestion is to try clearing the cache by deleting the `cache` folder. if that doesn't work, can you provide some more details so i can reproduce?

**Comment by joeyfigaro** [comment]
@maxlapides I don't *think* it's a caching issue - should be a graceful error handling issue. Some more details:

**HTML**
```handlebars
<a class="logo" title="<y>.com" href="https://<y>.com">
    <img width="157" src="https://<y>.com/img/email/logo-white.png" alt="<y>" title="<y>"/>
</a>
```

**Steps**
- Updated filename for image from `logo-white.png` to `logo-white-@2x.png` in project repository
- Merged changes into master to deploy image to the web
- Update html and save while waiting on deploy to complete 
- Asset is not yet available (because the deploy is pending) resulting in a broken URL
- Gulp crashes

**Comment by joeyfigaro** [comment]
If `file` is undefined, maybe resort to a dummy image from the package?

**Comment by maxlapides** [comment]
@joeyfigaro i just published v0.5.11, which should do a better job handling non-existent images. i'm not 100% sure this covers your error case, but could you give it a shot and let me know?

(i will also consider the dummy image idea!)

**Comment by joeyfigaro** [comment]
@maxlapides Tryin' it out now. 🎉

**Comment by joeyfigaro** [comment]
@maxlapides Much better! Tried with a 404 url.

```bash
error:  Error: ENOENT: no such file or directory, scandir '/Users/<a>/Repositories/<x>/<y>/node_modules/node-sass/vendor'
```

**Comment by maxlapides** [comment]
@joeyfigaro weird that it's not giving you a more meaningful error (it shouldn't be saying anything about node-sass here), but hey, at least it's working!

**Comment by joeyfigaro** [comment]
@maxlapides Looks like it originated from here: `dovetailer/lib/styles.js:11:22`

Thanks a million.
